apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-reader
  namespace: test-ns
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-reader
  template:
    metadata:
      labels:
        app: log-reader
    spec:
      containers:
      - name: log-reader
        image: jangirjs/random-log-printer:v0.1
        env:
        - name: FILE_LOCATION
          value: "loghub/HDFS/HDFS_2k.log"
        - name: N_LINES
          value: "10"  # Example value for N
        - name: SLEEP_TIME
          value: "20"
        - name: GITHUB_URL
          value: "https://github.com/logpai/loghub"



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-reader
  namespace: test-ns-1
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-reader
  template:
    metadata:
      labels:
        app: log-reader
    spec:
      containers:
      - name: log-reader
        image: jangirjs/random-log-printer:v0.1
        env:
        - name: FILE_LOCATION
          value: "loghub/HDFS/HDFS_2k.log"
        - name: N_LINES
          value: "10"  # Example value for N
        - name: SLEEP_TIME
          value: "20"
        - name: GITHUB_URL
          value: "https://github.com/logpai/loghub"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-reader
  namespace: test-ns-2
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-reader
  template:
    metadata:
      labels:
        app: log-reader
    spec:
      containers:
      - name: log-reader
        image: jangirjs/random-log-printer:v0.1
        env:
        - name: FILE_LOCATION
          value: "loghub/HDFS/HDFS_2k.log"
        - name: N_LINES
          value: "10"  # Example value for N
        - name: SLEEP_TIME
          value: "20"
        - name: GITHUB_URL
          value: "https://github.com/logpai/loghub"

---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-reader
  namespace: test-ns-3
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-reader
  template:
    metadata:
      labels:
        app: log-reader
    spec:
      containers:
      - name: log-reader
        image: jangirjs/random-log-printer:v0.1
        env:
        - name: FILE_LOCATION
          value: "loghub/HDFS/HDFS_2k.log"
        - name: N_LINES
          value: "10"  # Example value for N
        - name: SLEEP_TIME
          value: "20"
        - name: GITHUB_URL
          value: "https://github.com/logpai/loghub"